external/yuki/image.go
internal/model/yuki.go
server/handler/misc.go
server/router.go
server/routes/misc.go

- 在 InitRoute 函数中添加了对杂项路由的初始化
- 增加图片上传API。
- 检查上传图片响应状态码。
- 修复获取相册名称错误的bug。

Yuki-image

---

internal/dao/problem.go
internal/model/misc.go
server/handler/problem.go

- 实现了 FieldList 类型及其相关方法，包括 Exist、Value 和 Set。
- FieldList 用于处理多个同类型字段的集合，提供了对字段存在性和值的访问，以及设置字段值的功能。当尝试设置不匹配类型或数量的值时，会返回错误。
- 修改 ProblemWhere 结构体，将 Tag 字段类型从 model.Field[uint64] 改为 model.FieldList[uint64]
- 更新 generateProblemWhereCondition 函数，以支持多标签查询
- 修改 parseProblemWhere 函数，处理多个标签参数

feat(problem): 改进题目筛选功能，支持多标签查询

---

server/middlewares/auth.go

- 重构 getUserRole 函数，使用 uint64 类型的用户 ID 作为参数
- 优化错误处理，提高用户体验
- 调整中间件逻辑，提高代码可读性和维护性

feat(auth): 优化 Token 验证逻辑

---

internal/service/blog/select.go

- 修改了 SelectById 和 Select 函数的权限判断逻辑
- 对于非公开博客，允许博客所有者查看：对于blogList，若用户不为管理员时，只能查询到公开博客，若用户查询自己的博客，则可以查询到所有博客。对于blogById，若用户不为管理员，只可查询公开博客或自己的所有博客。
- 优化了查询条件，减少了不必要的循环遍历

perf(blog): 优化博客查询逻辑

---

Dockerfile
docker-compose.yaml

- 新增 Dockerfile 用于构建 StuOJ 服务镜像
- 新增 docker-compose.yaml 用于定义容器服务
- 配置 Go 代理、时区等环境
- 优化镜像构建过程，减小最终镜像大小

build: 添加 Dockerfile 和 docker-compose.yaml 文件

---

internal/service/problem/update.go

- 将 p0 替换为 p，确保更新操作作用于正确的对象
- 优化代码结构，提高代码可读性和维护性

refactor(internal/service/problem): 修复更新题目时的代码错误

---

external/neko/misc.go
external/neko/neko.go
external/neko/problem.go
external/neko/solution.go
external/neko/testcase.go
internal/model/neko.go
internal/service/misc/misc.go
internal/service/problem/misc.go
server/handler-admin/problem.go
server/handler/misc.go
server/routes/admin.go
server/routes/misc.go

This pull request introduces several new functionalities and refactors existing code to improve the handling of responses and add new features. The most important changes include adding joke and translation functionalities, updating response handling, and extending the API routes.
New functionalities:
* [`external/neko/misc.go`](diffhunk://#diff-d6042011c089be93bb6ef08ec8d32637176106434b33f30395248f87ee7b4ee0R1-R28): Added the `TellJoke` function to fetch jokes from an external service.
* [`external/neko/problem.go`](diffhunk://#diff-8c83e7dfde6bf568f5a1649bc6524629e3fe39aefc757adde7ad24d4ba561126L26-R60): Added the `TranslateProblem` function to handle problem translation requests.
* [`internal/service/misc/misc.go`](diffhunk://#diff-2d05f4c8667bd81fbe52a6cae56c56bfc607ad0c4ff7b1193e47d25 …

Feat: Add joke and translation functionalities

---

server/handler-admin/problem.go
server/handler-admin/solution.go

- 移除题目添加和修改接口中的 Source 和 Hint 字段的 required 校验
- 更新题解添加接口参数，去除 optional 标记

refactor(server): 调整题目和题解相关接口参数

---

server/handler-admin/problem.go

移除了 ReqProblemAdd 结构体中 Difficulty 和 Status 字段的 required 验证。
这样可以允许在添加问题时，这两个字段变为可选字段，增加了接口的灵活性。

refactor(server): 移除问题添加接口中的非必需字段验证

---

config.yaml
go.mod
go.sum
internal/conf/conf.go
internal/conf/email.go
internal/entity/user.go
internal/service/user/statistics.go
server/handler-admin/user.go
server/handler/misc.go
server/handler/user.go
server/routes/misc.go
utils/email.go

Introduce email format validation, verification code generation, and validation for user registration and password changes. Update user structure to use a new Email type and enhance related services and handlers. Implement email configuration and integrate caching for verification codes.

Add email verification and code functionality

---

server/handler/blog.go

- 移除了 ReqBlogSave 结构体中非必需字段的 binding 标签
- 修改了 BlogUpload、BlogEdit 和 BlogRemove 接口中的错误响应
使用 model.RespError 替代 model.RespOk 来返回错误信息
- 优化了参数错误时的响应处理

refactor(server): 优化博客相关接口的错误处理和参数验证

---

internal/dao/blog.go
internal/dao/comment.go
internal/dao/problem.go
internal/dao/submission.go
internal/dao/user.go
internal/service/blog/select.go
internal/service/comment/select.go
internal/service/problem/select.go
internal/service/record/select.go
internal/service/user/select.go
server/handler-admin/user.go
server/handler/blog.go
server/handler/comment.go
server/handler/problem.go
server/handler/record.go

将分页逻辑移至专门用于问题、博客、提交内容、用户和评论的结构中。更新相关函数以利用这些结构，提高代码的可重用性和可维护性。默认分页参数可提升整个应用程序的可用性。

数据库查询优化：将page、size字段也解析入Where中

---

internal/service/problem/select.go

- 移除 SelectById 函数中的条件判断，简化代码结构
- 使用 SelectProblemById 替代 SelectProblem 方法，直接通过 ID 查询题目
- 对非公开题目的处理逻辑进行调整，提高代码可读性

refactor(internal/service/problem): 优化题目查询逻辑

---

internal/entity/user.go

This pull request includes changes to the `internal/entity/user.go` file, specifically focusing on updating and expanding the role definitions and their corresponding string representations. The most important changes include redefining the `Role` constants, adding new roles, and refactoring the `String` method to use a map for role names.
Role definitions update:
* Updated the `Role` constants to include new roles such as `RoleMuted`, `RoleVip`, and `RoleEditor`, and reassigned the integer values for all roles.
* Added a `roleNames` map to store the string representations of each role, improving the maintainability and readability of the code.
Refactoring:
* Refactored the `String` method to use the `roleNames` map for converting roles to their string representations, simplifying the …

Refactor user status

---

server/middlewares/auth.go

- 优化了 TokenAuthUser、TokenAuthAdmin 和 TokenAuthRoot 三个中间件的逻辑
- 使用 GetUserInfo 函数统一获取用户角色信息
- 调整了错误响应的 HTTP 状态码和错误信息
- 简化了代码结构，提高了可维护性

refactor(auth): 重构用户权限验证中间件

---

internal/bootstrap/config.go
internal/bootstrap/db.go
internal/bootstrap/judge0.go
internal/bootstrap/neko.go
internal/bootstrap/server.go
internal/bootstrap/yuki.go
internal/db/db.go
internal/db/migrate.go
internal/db/sqldb.go
internal/entity/blog.go
internal/entity/comment.go
internal/entity/history.go
internal/entity/judgement.go
internal/entity/language.go
internal/entity/problem.go
internal/entity/problem_tag.go
internal/entity/solution.go
internal/entity/submission.go
internal/entity/tag.go
internal/entity/testcase.go
internal/entity/user.go
internal/service/judge/submit_async.go
internal/service/judge/submit_wait.go
internal/service/judge/testrun.go
server/middlewares/auth.go

This pull request includes several changes to the codebase, focusing on updating log messages to Chinese, refactoring database initialization, and improving entity definitions. The most important changes are grouped by theme below:
* Updated log messages in `internal/bootstrap/config.go`, `db.go`, `judge0.go`, `neko.go`, `server.go`, and `yuki.go` to Chinese. [[1]](diffhunk://#diff-c4eeb899534be2a003f2d829772729a5f7f8c5979d919fee656dd985e20b07baL11-R14) [[2]](diffhunk://#diff-ce3bdcc4739feb35fe6781d43b17b195609b6d67bfc7e9dac4097a9fda317b14L11-R14) [[3]](diffhunk://#diff-a5a916304383764a1ae8bfd6fef2bc725cebab15df5fb639860ecccca83313e2L15-R30) [[4]](diffhunk://#diff-c9a87c1c3708594d08f9b7cf49ee4d31b59528a8793483a45dbffee9e14a7aebL12-R15) …

Update gorm model and add database auto migrate

---

internal/bootstrap/judge0.go
internal/dao/language.go
internal/service/judge/submit_async.go
internal/service/judge/submit_wait.go
internal/service/judge/testrun.go
internal/service/language/select.go
internal/service/language/update.go
server/handler/judge.go

- 新增 LanguageWhere 结构体用于语言查询条件
- 实现 generateLanguageWhereCondition 函数生成查询条件
- 修改 SelectLanguage 函数支持条件查询
- 新增 UpdateLanguage 函数实现语言更新
- 更新服务层和处理层以支持新的查询和更新功能
- 修改了 language 包的 Select 函数，增加 role 参数
- 根据用户角色决定是否隐藏语言列表中的 MapId 字段
- 在 judge 包的 JudgeLanguageList 函数中集成新逻辑
- 将函数 SelectLanguage 的注释从"查询所有语言"改为"查询语言"
- 优化了数据库操作，改为增删结合的方式
- 保留了已有的语言记录，仅更新或插入新的语言
- 在提交代码前增加语言状态检查，确保语言可用
- 使用语言映射 ID 替代原始语言 ID 进行评测
- 修复了使用禁用语言提交代码的问题
- 新增 SelectById 函数，用于根据 ID 查询语言信息

优化语言查询；新增语言更新；根据用户隐藏映射ID；增加语言状态检查并处理语言映射；增加通过 ID 查询语言的功能；优化语言初始化逻辑 

---

internal/dao/blog.go
internal/dao/problem.go
internal/dao/submission.go
internal/service/blog/select.go
internal/service/problem/select.go
server/handler/blog.go
server/handler/problem.go
server/handler/record.go

- 更新 generateSubmissionWhereConditionWithNoPage 函数，支持多问题和多用户的查询
- 更新 generateBlogWhereConditionWithNoPage 函数，支持多对多查询
- 改进博客、题目的Select 函数，根据用户角色设置查询条件
- 在 ProblemWhere 结构中添加 UserId 字段，用于筛选用户相关的题目

提交记录的批量查询；优化博客查询功能 ；增加用户筛选查询题目功能并优化题目列表逻辑

---

server/handler/user.go

- 为用户名、密码、邮箱等字段添加最小和最大长度限制
- 优化验证码长度的校验规则
- 统一签名长度的校验规则

refactor(server): 优化用户相关接口的参数校验规则

---

internal/entity/blog.go
internal/service/blog/delete.go
internal/service/blog/insert.go
internal/service/blog/select.go
internal/service/blog/update.go
server/handler/blog.go
server/routes/blog.go

- 修改了博客状态常量的命名方式
- 优化了博客上传、编辑、删除等操作的逻辑
- 移除了博客提交功能，改为直接修改状态
- 调整了权限控制的实现方式
- 统一了错误信息的返回格式

refactor(blog): 重构博客相关逻辑

---

internal/service/blog/select.go
server/handler/blog.go

- 修改 SelectById 函数参数，使用 role 替代 admin 可变参数
- 优化权限判断逻辑，提高代码可读性
- 统一参数类型，提升代码一致性

refactor(blog): 重构博客查询接口

---

internal/service/blog/select.go

- 将 hideBlogContent 函数重命名为 cutBlogContent
- 修改 cutBlogContent 函数，将博客内容裁剪为 256 字符加省略号，而不是直接隐藏

refactor(blog): 优化博客内容显示

---

internal/model/blog.go
internal/model/comment.go
internal/model/language.go
internal/model/problem.go
internal/model/submission.go
internal/model/user.go

- 在 BlogWhere、CommentWhere、LanguageWhere、ProblemWhere、SubmissionWhere 和 UserWhere 结构体中添加 OrderBy 和 Order 字段
- 修改 Parse 方法以解析排序参数
- 更新 GenerateWhereWithNoPage 方法以应用排序
- 通过查询参数 "order" 和 "order_by" 实现自定义排序

feat(model): 为所有模型添加排序功能

---

internal/dao/problem.go
internal/service/problem/delete.go
internal/service/problem/insert.go
internal/service/problem/select.go
internal/service/problem/update.go
server/handler/problem.go
server/handler/tag.go
server/routes/problem.go

- 新增 SelectProblemByIdWithUser 函数，用于获取题目及其相关用户信息
- 在删除、插入、查询和更新题目标签时增加了用户权限验证逻辑
- 修复了普通用户可以操作非公开题目和他人题目的问题
- 优化了权限验证的逻辑，提高了系统安全性

fix(problem): 修复用户权限验证问题

---

internal/dao/problem.go

- 在 SelectProblem 函数中增加了对问题标签的查询和处理
- 使用辅助结构体 auxiliaryProblem 来简化查询结果的处理
- 通过子查询获取问题标签 ID，并将其解析为 uint64 类型数组
- 优化了查询性能，减少了数据库访问次数

feat(dao): 优化题目查询功能

---

internal/service/record/select.go
server/handler/record.go

- 修改 Select 和 SelectBySubmissionId 函数，使用 role 参数替代 hideCode 参数
- 根据用户角色决定是否隐藏源代码，提高系统灵活性
- 移除不必要的 bool 参数，简化函数调用

refactor(record): 重构记录查询功能并优化权限控制

---

external/judge0/judge.go
internal/dao/submission.go
internal/service/judge/submit_async.go
server/handler/judge.go

- 优化了 asyncSubmit 函数，增加了错误处理和并发控制
- 重构了 asyncJudge 函数，移除了通道通信，改为返回值
- 新增了 UpdateSubmissionByIdAndInsertJudgements 函数，用于批量插入评测结果
- 替换了 ioutil.ReadAll 为 io.ReadAll，以提高代码的可维护性

refactor(judge): 重构异步提交流程

---

internal/dao/collection.go
internal/db/db.go
internal/entity/collection.go
internal/model/collection.go
internal/model/problem.go
internal/service/collection/insert.go
internal/service/collection/select.go
internal/service/collection/update.go
internal/service/problem/select.go
server/handler/collection.go
server/routes/problem.go
utils/misc.go

- 使用 slices.Contains 函数替代手动遍历切片查找元素
- 优化了 collection 和 problem 模块中的用户权限判断逻辑
- 提高了代码可读性和性能
- 将 Id 字段类型从 Field[uint64] 改为 FieldList[uint64]
- 更新 GenerateWhereWithNoPage 方法，使用 IN 查询替代等值查询
- 优化查询条件的构建逻辑，提高可读性和性能
- 在 Collection 结构中添加 Problem 字段，用于返回题目信息
- 在查询题单详情时，根据题单内的题目 ID 列表查询相关题目信息
- 优化了题单详情的查询逻辑，增加了对题目信息的获取
- 新增 UpdateCollectionProblem 函数用于更新题单题目信息
- 实现 CollectionModifyProblem 处理函数以处理修改题单题目的请求
- 添加相关路由和权限验证逻辑
- 在集合查询中添加题目顺序排序
- 新增 Uint64SliceToString 工具函数
- 使用 FIELD 函数对题目进行自定义排序

优化用户权限判断逻辑；重构 ProblemWhere 结构体和查询逻辑；在获取题单中添加题目数据；题单题目增加序号项；添加修改题单题目接口；增加修改题单题目顺序功能
